### ISSUE TITLE
Super Drag is currently broken on Firefox Nightly(since 2014-09-16)

### ISSUE THREAD

**Issue by BenYeeHua** [cyberscorpio/superdrag#8]
Hi, just want to tell you that it is broken on Firefox Nightly, because of this change.
You may wanna check your other addon as well.

Bug 1001090 - Implement ES6 "temporal dead zone" for let and const
https://bugzilla.mozilla.org/show_bug.cgi?id=1001090

And, thank for making this addons. :)

**Comment by BenYeeHua** [comment]
Hi, I just tested it, and it works well, thank for the fix in such a short time. :D

**Comment by cyberscorpio** [comment]
Thanks for your pointing out where the problem is :)
